### ISSUE TITLE
Error running the script in IDA 9

### ISSUE THREAD

**Issue by seifreed** [ke0z/VulChatGPT#3]
Hello,

It seems this plugin doesn't work:

```
Traceback (most recent call last):
  File "C:\Program Files\Python310\Lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python310\Lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Program Files/IDA Professional 9.0/plugins/VulChatGPT.py", line 284, in query_model
    except openai.InvalidRequestError as e:
AttributeError: module 'openai' has no attribute 'InvalidRequestError'. Did you mean: 'BadRequestError'?
```

The openai module it's installed:

```
PS C:\Users\Tinba\Documents\> pip show openai
Name: openai
Version: 1.57.4
Summary: The official Python library for the openai API
Home-page: https://github.com/openai/openai-python
Author:
Author-email: OpenAI <support@openai.com>
License: Apache-2.0
Location: c:\program files\python310\lib\site-packages
Requires: anyio, distro, httpx, jiter, pydantic, sniffio, tqdm, typing-extensions
Required-by: langchain-openai
```

**Comment by ke0z** [comment]
fixed in current version
